import { Badge } from "../model/Badge";
import { t } from "../i18n";

export const BADGE_CATALOG: Badge[] = [
  // --- Streaks ---
  {
    id: "first_step_hero",
    name: "First Step Hero",
    emoji: "👟",
    iconName: "footsteps",
    tagline: "The adventure begins!",
    description: "Completed your very first workout. The hardest part is starting!",
    category: "streak",
    gradientColors: ["#3B82F6", "#1D4ED8"],
  },
  {
    id: "back_to_back_beast",
    name: "Back-to-Back Beast",
    emoji: "🔄",
    iconName: "repeat",
    tagline: "No fluke here!",
    description: "Completed a 2-day workout streak. Day 1 was no accident—double trouble!",
    category: "streak",
    gradientColors: ["#06B6D4", "#0369A1"],
  },
  {
    id: "spaghetti_legs",
    name: "Spaghetti Legs",
    emoji: "🍝",
    iconName: "flame",
    tagline: "Wobbly but victorious!",
    description: "Crushed a 3-day workout streak. Your legs may be pasta, but your spirit is iron!",
    category: "streak",
    gradientColors: ["#F59E0B", "#D97706"],
  },
  {
    id: "workweek_warrior",
    name: "Workweek Warrior",
    emoji: "💼",
    iconName: "briefcase",
    tagline: "Monday to Friday crushed!",
    description: "Achieved a 5-day workout streak. You conquered the entire working week with sweat!",
    category: "streak",
    gradientColors: ["#10B981", "#047857"],
  },
  {
    id: "sweat_monster",
    name: "Sweat Monster",
    emoji: "👾",
    iconName: "water",
    tagline: "7 days of pure heat!",
    description: "Achieved a full 7-day workout streak. You are officially unstoppable.",
    category: "streak",
    gradientColors: ["#10B981", "#059669"],
  },
  {
    id: "fortnight_of_fire",
    name: "Fortnight of Fire",
    emoji: "🔥",
    iconName: "bonfire",
    tagline: "Two weeks blazing!",
    description: "Maintained a 14-day workout streak. Two uninterrupted weeks of pure momentum!",
    category: "streak",
    gradientColors: ["#F97316", "#C2410C"],
  },
  {
    id: "habit_machine",
    name: "Habit Machine",
    emoji: "🤖",
    iconName: "hardware-chip",
    tagline: "Hardwired for gains!",
    description: "Reached a 21-day workout streak. Science says 21 days builds a habit—you are automatic!",
    category: "streak",
    gradientColors: ["#6366F1", "#4338CA"],
  },
  {
    id: "unstoppable_dynamo",
    name: "Unstoppable Dynamo",
    emoji: "⚡️",
    iconName: "flash",
    tagline: "30-day legendary status!",
    description: "Maintained a 30-day workout streak. You've forged a superpower habit!",
    category: "streak",
    gradientColors: ["#8B5CF6", "#6D28D9"],
  },
  {
    id: "iron_will",
    name: "Iron Will",
    emoji: "🦏",
    iconName: "shield",
    tagline: "Unbreakable discipline!",
    description: "Maintained a 60-day workout streak. Two solid months of relentless determination!",
    category: "streak",
    gradientColors: ["#475569", "#1E293B"],
  },
  {
    id: "quarterly_crusher",
    name: "Quarterly Crusher",
    emoji: "👑",
    iconName: "trophy",
    tagline: "Quarter of greatness!",
    description: "Reached a 90-day workout streak. 3 solid months of cardio supremacy!",
    category: "streak",
    gradientColors: ["#EAB308", "#A16207"],
  },
  {
    id: "half_year_hero",
    name: "Half-Year Hero",
    emoji: "🥋",
    iconName: "medal",
    tagline: "Halfway to immortality!",
    description: "Achieved a 180-day workout streak. 6 continuous months of crushing it daily!",
    category: "streak",
    gradientColors: ["#EC4899", "#BE185D"],
  },
  {
    id: "sun_god_of_sweat",
    name: "Sun God of Sweat",
    emoji: "☀️",
    iconName: "sunny",
    tagline: "A full orbit of gains!",
    description: "A legendary 365-day workout streak. A full year without missing a beat—fitness deity status!",
    category: "streak",
    gradientColors: ["#F59E0B", "#B45309"],
  },
  {
    id: "weekend_warrior",
    name: "Weekend Warrior",
    emoji: "🛡️",
    iconName: "shield-checkmark",
    tagline: "No days off for greatness!",
    description: "Completed workouts on both Saturday and Sunday in the same weekend.",
    category: "streak",
    gradientColors: ["#EC4899", "#BE185D"],
  },

  // --- Volume & Time ---
  {
    id: "ten_minute_tornado",
    name: "Ten-Minute Tornado",
    emoji: "🌪️",
    iconName: "timer",
    tagline: "Double-digit endurance!",
    description: "Clocked 10 total minutes of high-intensity sweat time.",
    category: "volume",
    gradientColors: ["#06B6D4", "#0891B2"],
  },
  {
    id: "hour_of_power",
    name: "Hour of Power",
    emoji: "🔋",
    iconName: "battery-charging",
    tagline: "60 minutes of greatness!",
    description: "Completed 60 total minutes of cumulative interval training.",
    category: "volume",
    gradientColors: ["#EAB308", "#CA8A04"],
  },
  {
    id: "century_club",
    name: "Century Club",
    emoji: "💯",
    iconName: "ribbon",
    tagline: "100 intervals conquered!",
    description: "Powered through 100 total individual workout intervals.",
    category: "volume",
    gradientColors: ["#EF4444", "#B91C1C"],
  },

  // --- Feats & Timing ---
  {
    id: "early_bird",
    name: "Early Bird Gets the Sweat",
    emoji: "🌅",
    iconName: "sunny",
    tagline: "Rise and shine champion!",
    description: "Completed a workout before 8:00 AM. Winning before the day even starts!",
    category: "timing",
    gradientColors: ["#F97316", "#EA580C"],
  },
  {
    id: "night_owl",
    name: "Night Owl Burn",
    emoji: "🦉",
    iconName: "moon",
    tagline: "Midnight grind mode!",
    description: "Completed a workout after 8:00 PM. Lighting up the night with sweat!",
    category: "timing",
    gradientColors: ["#6366F1", "#4338CA"],
  },
  {
    id: "iron_lungs",
    name: "Iron Lungs",
    emoji: "🫁",
    iconName: "heart",
    tagline: "Endurance beast!",
    description: "Completed a grueling workout session with 5 or more rounds.",
    category: "feat",
    gradientColors: ["#14B8A6", "#0D9488"],
  },
  {
    id: "custom_creator",
    name: "Custom Creator",
    emoji: "🎨",
    iconName: "construct",
    tagline: "Master architect!",
    description: "Built and finished your own custom crafted interval timer.",
    category: "feat",
    gradientColors: ["#A855F7", "#7E22CE"],
  },

  // --- Viral Sharing & Community ---
  {
    id: "megaphone_maestro",
    name: "Megaphone Maestro",
    emoji: "📣",
    iconName: "megaphone",
    tagline: "Spread the good word!",
    description: "Shared your very first workout, timer, or badge with the world.",
    category: "sharing",
    gradientColors: ["#38BDF8", "#0284C7"],
  },
  {
    id: "squad_recruiter",
    name: "Squad Recruiter",
    emoji: "👯",
    iconName: "chatbubble-ellipses",
    tagline: "Misery loves company!",
    description: "Shared a workout or custom timer directly to a friend via Messages/SMS.",
    category: "sharing",
    gradientColors: ["#34D399", "#059669"],
  },
  {
    id: "chain_letter_of_gains",
    name: "Chain Letter of Gains",
    emoji: "✉️",
    iconName: "mail",
    tagline: "Forward or skip leg day!",
    description: "Shared an interval timer via Email or direct invite link.",
    category: "sharing",
    gradientColors: ["#FB923C", "#C2410C"],
  },
  {
    id: "hype_machine",
    name: "Hype Machine",
    emoji: "🚀",
    iconName: "rocket",
    tagline: "Contagious energy!",
    description: "Shared 5 workouts, badges, or timers with friends.",
    category: "sharing",
    gradientColors: ["#F43F5E", "#BE123C"],
  },
  {
    id: "sweat_influencer",
    name: "Sweat Influencer",
    emoji: "🤳",
    iconName: "camera",
    tagline: "Basically famous!",
    description: "Shared 10 times across your fitness network. Influencer status unlocked!",
    category: "sharing",
    gradientColors: ["#EC4899", "#9D174D"],
  },
  {
    id: "chief_fitness_officer",
    name: "Chief Fitness Officer",
    emoji: "💼",
    iconName: "briefcase",
    tagline: "Promoted to management!",
    description: "Shared 25 times! Leading the charge to get everyone moving.",
    category: "sharing",
    gradientColors: ["#6366F1", "#3730A3"],
  },
  {
    id: "viral_phenomenon",
    name: "Viral Phenomenon",
    emoji: "🌐",
    iconName: "globe",
    tagline: "Trending everywhere!",
    description: "50 total shares! You are officially breaking the fitness internet.",
    category: "sharing",
    gradientColors: ["#8B5CF6", "#5B21B6"],
  },
  {
    id: "cult_leader_of_cardio",
    name: "Cult Leader of Cardio",
    emoji: "🕯️",
    iconName: "flame",
    tagline: "Drink the electrolyte Kool-Aid!",
    description: "100 total shares! You've amassed a loyal following of cardio disciples.",
    category: "sharing",
    gradientColors: ["#D946EF", "#86198F"],
  },
  {
    id: "galactic_ambassador",
    name: "Galactic Ambassador of Gains",
    emoji: "🛸",
    iconName: "planet",
    tagline: "Spreading HIIT to the stars!",
    description: "1,000 shares! Interstellar legend status achieved.",
    category: "sharing",
    gradientColors: ["#F59E0B", "#7C2D12"],
  },
  {
    id: "imported_gains",
    name: "Workout Pen Pal",
    emoji: "📬",
    iconName: "gift",
    tagline: "Shared sweat is best sweat!",
    description: "Successfully imported and completed a workout shared by a friend.",
    category: "sharing",
    gradientColors: ["#14B8A6", "#0F766E"],
  },

  // --- Discovery & Exploration ---
  {
    id: "curious_explorer",
    name: "Curious Explorer",
    emoji: "🔍",
    iconName: "search",
    tagline: "Uncovering new movements!",
    description: "Searched the exercise library or filtered by body parts to discover custom exercises.",
    category: "discovery",
    gradientColors: ["#06B6D4", "#0891B2"],
  },
  {
    id: "anatomical_master",
    name: "Anatomical Master",
    emoji: "🧭",
    iconName: "compass",
    tagline: "Total body knowledge!",
    description: "Explored exercises across at least 5 different body parts and joint areas.",
    category: "discovery",
    gradientColors: ["#3B82F6", "#1D4ED8"],
  },
  {
    id: "movement_scholar",
    name: "Movement Scholar",
    emoji: "🔬",
    iconName: "book",
    tagline: "Perfecting technique & form!",
    description: "Inspected detailed form cues and instructions for 10 different exercises.",
    category: "discovery",
    gradientColors: ["#8B5CF6", "#6D28D9"],
  },

  // --- Corrective & Physical Therapy ---
  {
    id: "rehab_rookie",
    name: "Rehab Rookie",
    emoji: "🩹",
    iconName: "bandage",
    tagline: "Smart recovery begins!",
    description: "Completed your very first corrective or physical therapy exercise routine.",
    category: "corrective",
    gradientColors: ["#10B981", "#059669"],
  },
  {
    id: "bulletproof_joints",
    name: "Bulletproof Joints",
    emoji: "🛡️",
    iconName: "shield-checkmark",
    tagline: "Resilient & unbreakable!",
    description: "Completed 5 corrective, mobility, or physical therapy workout sessions.",
    category: "corrective",
    gradientColors: ["#059669", "#047857"],
  },
  {
    id: "posture_perfectionist",
    name: "Posture Perfectionist",
    emoji: "🧘",
    iconName: "body",
    tagline: "Aligned from head to toe!",
    description: "Completed 15 physical therapy & corrective intervals targeting posture and joint stability.",
    category: "corrective",
    gradientColors: ["#F59E0B", "#B45309"],
  },
  {
    id: "iron_alignment",
    name: "Iron Alignment",
    emoji: "🏛️",
    iconName: "fitness",
    tagline: "Master of functional health!",
    description: "Completed 10 full corrective or physical therapy workout routines.",
    category: "corrective",
    gradientColors: ["#6366F1", "#312E81"],
  },
];

/**
 * Returns a localized copy of a badge according to current active locale.
 */
export function getLocalizedBadge(badge: Badge): Badge {
  return {
    ...badge,
    name: t(`badges.${badge.id}.name`, { defaultValue: badge.name }),
    tagline: t(`badges.${badge.id}.tagline`, { defaultValue: badge.tagline }),
    description: t(`badges.${badge.id}.description`, { defaultValue: badge.description }),
  };
}

/**
 * Returns the full catalog of badges with localized names, taglines, and descriptions.
 */
export function getLocalizedBadges(): Badge[] {
  return BADGE_CATALOG.map(getLocalizedBadge);
}

