import { Badge } from "../model/Badge";

export const BADGE_CATALOG: Badge[] = [
  // --- Streaks ---
  {
    id: "first_step_hero",
    name: "First Step Hero",
    emoji: "👟",
    iconName: "footsteps",
    tagline: "The adventure begins!",
    description: "Completed your very first workout. The hardest part is starting!",
    category: "streak",
    gradientColors: ["#3B82F6", "#1D4ED8"],
  },
  {
    id: "spaghetti_legs",
    name: "Spaghetti Legs",
    emoji: "🍝",
    iconName: "flame",
    tagline: "Wobbly but victorious!",
    description: "Crushed a 3-day workout streak. Your legs may be pasta, but your spirit is iron!",
    category: "streak",
    gradientColors: ["#F59E0B", "#D97706"],
  },
  {
    id: "sweat_monster",
    name: "Sweat Monster",
    emoji: "👾",
    iconName: "water",
    tagline: "7 days of pure heat!",
    description: "Achieved a full 7-day workout streak. You are officially unstoppable.",
    category: "streak",
    gradientColors: ["#10B981", "#059669"],
  },
  {
    id: "unstoppable_dynamo",
    name: "Unstoppable Dynamo",
    emoji: "⚡️",
    iconName: "flash",
    tagline: "30-day legendary status!",
    description: "Maintained a 30-day workout streak. You've forged a superpower habit!",
    category: "streak",
    gradientColors: ["#8B5CF6", "#6D28D9"],
  },
  {
    id: "weekend_warrior",
    name: "Weekend Warrior",
    emoji: "🛡️",
    iconName: "shield-checkmark",
    tagline: "No days off for greatness!",
    description: "Completed workouts on both Saturday and Sunday in the same weekend.",
    category: "streak",
    gradientColors: ["#EC4899", "#BE185D"],
  },

  // --- Volume & Time ---
  {
    id: "ten_minute_tornado",
    name: "Ten-Minute Tornado",
    emoji: "🌪️",
    iconName: "timer",
    tagline: "Double-digit endurance!",
    description: "Clocked 10 total minutes of high-intensity sweat time.",
    category: "volume",
    gradientColors: ["#06B6D4", "#0891B2"],
  },
  {
    id: "hour_of_power",
    name: "Hour of Power",
    emoji: "🔋",
    iconName: "battery-charging",
    tagline: "60 minutes of greatness!",
    description: "Completed 60 total minutes of cumulative interval training.",
    category: "volume",
    gradientColors: ["#EAB308", "#CA8A04"],
  },
  {
    id: "century_club",
    name: "Century Club",
    emoji: "💯",
    iconName: "ribbon",
    tagline: "100 intervals conquered!",
    description: "Powered through 100 total individual workout intervals.",
    category: "volume",
    gradientColors: ["#EF4444", "#B91C1C"],
  },

  // --- Feats & Timing ---
  {
    id: "early_bird",
    name: "Early Bird Gets the Sweat",
    emoji: "🌅",
    iconName: "sunny",
    tagline: "Rise and shine champion!",
    description: "Completed a workout before 8:00 AM. Winning before the day even starts!",
    category: "timing",
    gradientColors: ["#F97316", "#EA580C"],
  },
  {
    id: "night_owl",
    name: "Night Owl Burn",
    emoji: "🦉",
    iconName: "moon",
    tagline: "Midnight grind mode!",
    description: "Completed a workout after 8:00 PM. Lighting up the night with sweat!",
    category: "timing",
    gradientColors: ["#6366F1", "#4338CA"],
  },
  {
    id: "iron_lungs",
    name: "Iron Lungs",
    emoji: "🫁",
    iconName: "heart",
    tagline: "Endurance beast!",
    description: "Completed a grueling workout session with 5 or more rounds.",
    category: "feat",
    gradientColors: ["#14B8A6", "#0D9488"],
  },
  {
    id: "custom_creator",
    name: "Custom Creator",
    emoji: "🎨",
    iconName: "construct",
    tagline: "Master architect!",
    description: "Built and finished your own custom crafted interval timer.",
    category: "feat",
    gradientColors: ["#A855F7", "#7E22CE"],
  },
];
